"""update lecture tables

Revision ID: 177b16487c61
Revises: e4d005c46dcf
Create Date: 2023-10-17 10:37:03.812425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177b16487c61'
down_revision = 'e4d005c46dcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_attribute', 'attr_subtitle')

    op.create_table('lecture_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('anchor', sa.String(), nullable=True),
    sa.Column('lecture_attribute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_attribute_id'], ['lecture_attribute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_links_id'), 'lecture_links', ['id'], unique=False)
    op.drop_index('ix_lecture_value_id', table_name='lecture_value')
    op.drop_table('lecture_value')

    op.add_column('lecture_attribute', sa.Column('attr_text', sa.Text(), nullable=True))
    op.drop_column('lecture_attribute', 'attr_number')
    op.add_column('lecture_attribute', sa.Column('attr_number', sa.INTEGER(), nullable=False))

    # op.alter_column('lecture_attribute', 'attr_number',
    #                 existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_attribute', sa.Column('attr_subtitle', sa.VARCHAR(), nullable=True))
    op.alter_column('lecture_attribute', 'attr_number',
                    existing_type=sa.INTEGER(), nullable=True)
    op.drop_column('lecture_attribute', 'attr_text')
    op.create_table('lecture_value',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('lecture_attribute_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_attribute_id'], ['lecture_attribute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lecture_value_id', 'lecture_value', ['id'], unique=False)
    op.drop_index(op.f('ix_lecture_links_id'), table_name='lecture_links')
    op.drop_table('lecture_links')
    # ### end Alembic commands ###
