"""rename column quantity_wibinar and delete column file_path

Revision ID: 17cbff25c501
Revises: e6ee2b8f3a72
Create Date: 2023-08-09 12:15:34.063207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cbff25c501'
down_revision = 'e6ee2b8f3a72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_item_temp',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.TEXT(), nullable=True),
                    sa.Column('subject_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.execute("INSERT INTO subject_item_temp SELECT id, text, subject_id FROM subject_item")
    op.drop_table('subject_item')
    op.rename_table('subject_item_temp', 'subject_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_item_temp',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.TEXT(), nullable=False),
                    sa.Column('subject_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.execute("INSERT INTO subject_item_temp SELECT id, text, subject_id FROM subject_item")
    op.drop_table('subject_item')
    op.rename_table('subject_item_temp', 'subject_item')
    # ### end Alembic commands ###

