"""added new fileds for instructions

Revision ID: 1a601a323691
Revises: e7caf57ddb2c
Create Date: 2023-09-21 15:32:50.839826

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1a601a323691'
down_revision = 'e7caf57ddb2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_instruction_category', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('subject_instruction_category', sa.Column('is_view', sa.Boolean(), nullable=True))
    op.add_column('subject_instruction_files', sa.Column('file_type', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'subject_instruction_category', ['category_name'])
    op.create_foreign_key(None, 'subject_instruction_category', 'subject', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_instruction_files', 'file_type')
    op.drop_constraint(None, 'subject_instruction_category', type_='foreignkey')
    op.drop_constraint(None, 'subject_instruction_category', type_='unique')
    op.drop_column('subject_instruction_category', 'is_view')
    op.drop_column('subject_instruction_category', 'number')
    op.drop_constraint(None, 'subject_instruction', type_='foreignkey')
    op.drop_column('subject_instruction', 'is_view')
    # ### end Alembic commands ###
