"""Added field mime type for attach files

Revision ID: 31dd3884b030
Revises: 5063405c8a8a
Create Date: 2023-07-21 15:44:24.620525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31dd3884b030'
down_revision = '5063405c8a8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_chat_attach_file', sa.Column('mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_chat_attach_file', 'mime_type')
    # ### end Alembic commands ###
