"""Create ModuleControl Tables

Revision ID: 5063405c8a8a
Revises: 9cf44218f00d
Create Date: 2023-07-19 16:30:23.803144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5063405c8a8a'
down_revision = '9cf44218f00d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
