"""Add read_by field to GroupChat and GroupChatAnswer tables

Revision ID: 73b7c8349566
Revises: ec395377a76f
Create Date: 2023-07-10 15:31:51.343521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b7c8349566'
down_revision = 'ec395377a76f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_chat', sa.Column('read_by', sa.String(), nullable=True))
    op.add_column('group_chat_answer', sa.Column('read_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_chat_answer', 'read_by')
    op.drop_column('group_chat', 'read_by')
    # ### end Alembic commands ###
