"""created tables

Revision ID: 7b022dfc5068
Revises: 
Create Date: 2023-09-27 15:41:40.916337

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7b022dfc5068'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_id'), 'course', ['id'], unique=False)
    op.create_table('module_control_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('with_video', 'only_test', name='modulecontroltypeoption'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_control_type_id'), 'module_control_type', ['id'], unique=False)
    op.create_table('question_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('test', 'boolean', 'test_with_photo', 'test_with_input', 'matching', 'open_question', 'multiple_choice', name='questiontypeoption'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_type_id'), 'question_type', ['id'], unique=False)
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('student', 'moder', 'teacher', 'curator', name='usertypeoption'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_type_id'), 'user_type', ['id'], unique=False)
    op.create_table('specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialization_id'), 'specialization', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('hashed_pass', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('exp_token', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.Date(), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('curator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curator_id'), 'curator', ['id'], unique=False)
    op.create_table('moder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moder_id'), 'moder', ['id'], unique=False)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_id'), 'teacher', ['id'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('curator_id', sa.Integer(), nullable=True),
    sa.Column('specialization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curator_id'], ['curator.id'], ),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    op.create_table('group_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('datetime_message', sa.DateTime(), autoincrement=True, nullable=True),
    sa.Column('fixed', sa.Boolean(), nullable=True),
    sa.Column('sender_type', sa.Enum('student', 'moder', 'teacher', 'curator', name='usertypeoption'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.Enum('alone', 'everyone', 'several', name='messagetypeoption'), nullable=False),
    sa.Column('read_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_chat_id'), 'group_chat', ['id'], unique=False)
    op.create_table('group_teacher_association',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'teacher_id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('educational_program', sa.String(), nullable=True),
    sa.Column('subject_area', sa.String(), nullable=True),
    sa.Column('field_of_study', sa.String(), nullable=True),
    sa.Column('group_leader', sa.Boolean(), autoincrement=True, nullable=False),
    sa.Column('date_added', sa.Date(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('specialization_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('quantity_lecture', sa.Integer(), nullable=True),
    sa.Column('quantity_seminar', sa.Integer(), nullable=True),
    sa.Column('quantity_test', sa.Integer(), nullable=True),
    sa.Column('quantity_module', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('specialization_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_table('group_chat_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('datetime_message', sa.DateTime(), autoincrement=True, nullable=True),
    sa.Column('sender_type', sa.Enum('student', 'moder', 'teacher', 'curator', name='usertypeoption'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('group_chat_id', sa.Integer(), nullable=True),
    sa.Column('read_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chat.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_chat_answer_id'), 'group_chat_answer', ['id'], unique=False)
    op.create_table('message_recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_chat_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chat.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_recipient_id'), 'message_recipient', ['id'], unique=False)
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_id'), 'module', ['id'], unique=False)
    op.create_table('participant_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_comment_id'), 'participant_comment', ['id'], unique=False)
    op.create_table('student_additional_subject',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'student_id')
    )
    op.create_table('subject_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('datetime_message', sa.DateTime(), autoincrement=True, nullable=True),
    sa.Column('fixed', sa.Boolean(), nullable=True),
    sa.Column('sender_type', sa.Enum('student', 'moder', 'teacher', 'curator', name='usertypeoption'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.Enum('alone', 'everyone', 'several', name='messagetypeoption'), nullable=False),
    sa.Column('read_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_chat_id'), 'subject_chat', ['id'], unique=False)
    op.create_table('subject_icon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon_path', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_icon_id'), 'subject_icon', ['id'], unique=False)
    op.create_table('subject_instruction_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('is_view', sa.Boolean(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index(op.f('ix_subject_instruction_category_id'), 'subject_instruction_category', ['id'], unique=False)
    op.create_table('subject_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_item_id'), 'subject_item', ['id'], unique=False)
    op.create_table('subject_teacher_association',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'teacher_id')
    )
    op.create_table('group_chat_attach_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('chat_message', sa.Integer(), nullable=True),
    sa.Column('chat_answer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_answer'], ['group_chat_answer.id'], ),
    sa.ForeignKeyConstraint(['chat_message'], ['group_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_chat_attach_file_id'), 'group_chat_attach_file', ['id'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('lesson_date', sa.DateTime(), nullable=True),
    sa.Column('lesson_end', sa.Time(), nullable=True),
    sa.Column('lesson_type', sa.Enum('lecture', 'seminar', 'test', 'online_lecture', 'online_seminar', 'module_control', 'exam', name='lessontypeoption'), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_id'), 'lesson', ['id'], unique=False)
    op.create_table('subject_chat_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('datetime_message', sa.DateTime(), autoincrement=True, nullable=True),
    sa.Column('sender_type', sa.Enum('student', 'moder', 'teacher', 'curator', name='usertypeoption'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('subject_chat_id', sa.Integer(), nullable=True),
    sa.Column('read_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_chat_id'], ['subject_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_chat_answer_id'), 'subject_chat_answer', ['id'], unique=False)
    op.create_table('subject_instruction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_view', sa.Boolean(), nullable=True),
    sa.Column('subject_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_category_id'], ['subject_instruction_category.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_instruction_id'), 'subject_instruction', ['id'], unique=False)
    op.create_table('subject_recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_chat_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_chat_id'], ['subject_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_recipient_id'), 'subject_recipient', ['id'], unique=False)
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_id'), 'lecture', ['id'], unique=False)
    op.create_table('lesson_missing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('missing', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_missing_id'), 'lesson_missing', ['id'], unique=False)
    op.create_table('lesson_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('lesson_type', sa.Enum('lecture', 'seminar', 'test', 'online_lecture', 'online_seminar', 'module_control', 'exam', name='lessontypeoption'), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_score_id'), 'lesson_score', ['id'], unique=False)
    op.create_table('module_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('set_timer', sa.Boolean(), nullable=False),
    sa.Column('timer', sa.Time(), nullable=True),
    sa.Column('timer_test', sa.Time(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('module_type_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['module_type_id'], ['module_control_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_control_id'), 'module_control', ['id'], unique=False)
    op.create_table('seminar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('set_timer', sa.Boolean(), nullable=True),
    sa.Column('timer', sa.Time(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seminar_id'), 'seminar', ['id'], unique=False)
    op.create_table('subject_chat_attach_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('chat_message', sa.Integer(), nullable=True),
    sa.Column('chat_answer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_answer'], ['subject_chat_answer.id'], ),
    sa.ForeignKeyConstraint(['chat_message'], ['subject_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_chat_attach_file_id'), 'subject_chat_attach_file', ['id'], unique=False)
    op.create_table('subject_instruction_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_instruction_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_instruction_id'], ['subject_instruction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_instruction_files_id'), 'subject_instruction_files', ['id'], unique=False)
    op.create_table('test_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('set_timer', sa.Boolean(), nullable=True),
    sa.Column('timer', sa.Time(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('show_answer', sa.Boolean(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_lesson_id'), 'test_lesson', ['id'], unique=False)
    op.create_table('video_lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_lecture_id'), 'video_lecture', ['id'], unique=False)
    op.create_table('video_seminar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_seminar_id'), 'video_seminar', ['id'], unique=False)
    op.create_table('lecture_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attr_type', sa.Enum('title', 'text', 'present', 'audio', 'picture', 'file', 'link', 'homework', name='lectureattributetype'), nullable=False),
    sa.Column('attr_title', sa.String(), nullable=False),
    sa.Column('attr_subtitle', sa.String(), nullable=True),
    sa.Column('attr_number', sa.Integer(), nullable=True),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_attribute_id'), 'lecture_attribute', ['id'], unique=False)
    op.create_table('lecture_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('check', sa.Boolean(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_score_id'), 'lecture_score', ['id'], unique=False)
    op.create_table('module_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_score', sa.Integer(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=True),
    sa.Column('module_control_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_control_id'], ['module_control.id'], ),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_question_id'), 'module_question', ['id'], unique=False)
    op.create_table('seminar_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_score', sa.Integer(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=True),
    sa.Column('seminar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_type.id'], ),
    sa.ForeignKeyConstraint(['seminar_id'], ['seminar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seminar_question_id'), 'seminar_question', ['id'], unique=False)
    op.create_table('student_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('number_attempt', sa.Integer(), nullable=True),
    sa.Column('module_control_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_control_id'], ['module_control.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_module_id'), 'student_module', ['id'], unique=False)
    op.create_table('student_seminar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('number_attempt', sa.Integer(), nullable=True),
    sa.Column('seminar_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seminar_id'], ['seminar.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_seminar_id'), 'student_seminar', ['id'], unique=False)
    op.create_table('student_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('number_attempt', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test_lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_test_id'), 'student_test', ['id'], unique=False)
    op.create_table('test_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_score', sa.Integer(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=True),
    sa.Column('test_lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_type.id'], ),
    sa.ForeignKeyConstraint(['test_lesson_id'], ['test_lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_question_id'), 'test_question', ['id'], unique=False)
    op.create_table('video_lecture_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('video_lecture_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['video_lecture_id'], ['video_lecture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_lecture_score_id'), 'video_lecture_score', ['id'], unique=False)
    op.create_table('video_seminar_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('video_seminar_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['video_seminar_id'], ['video_seminar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_seminar_score_id'), 'video_seminar_score', ['id'], unique=False)
    op.create_table('lecture_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('download_allowed', sa.Boolean(), nullable=True),
    sa.Column('lecture_attribute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_attribute_id'], ['lecture_attribute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_files_id'), 'lecture_files', ['id'], unique=False)
    op.create_table('lecture_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('lecture_attribute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_attribute_id'], ['lecture_attribute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_value_id'), 'lecture_value', ['id'], unique=False)
    op.create_table('module_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['module_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_answer_id'), 'module_answer', ['id'], unique=False)
    op.create_table('module_matching_right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['module_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_matching_right_id'), 'module_matching_right', ['id'], unique=False)
    op.create_table('seminar_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['seminar_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seminar_answer_id'), 'seminar_answer', ['id'], unique=False)
    op.create_table('seminar_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['seminar_question.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seminar_feedback_id'), 'seminar_feedback', ['id'], unique=False)
    op.create_table('seminar_matching_right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['seminar_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seminar_matching_right_id'), 'seminar_matching_right', ['id'], unique=False)
    op.create_table('test_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_answer_id'), 'test_answer', ['id'], unique=False)
    op.create_table('test_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_feedback_id'), 'test_feedback', ['id'], unique=False)
    op.create_table('test_matching_right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_matching_right_id'), 'test_matching_right', ['id'], unique=False)
    op.create_table('module_matching_left',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['module_question.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['module_matching_right.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_matching_left_id'), 'module_matching_left', ['id'], unique=False)
    op.create_table('seminar_feedback_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('seminar_feedback_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seminar_feedback_id'], ['seminar_feedback.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seminar_feedback_answer_id'), 'seminar_feedback_answer', ['id'], unique=False)
    op.create_table('seminar_matching_left',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['seminar_question.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['seminar_matching_right.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seminar_matching_left_id'), 'seminar_matching_left', ['id'], unique=False)
    op.create_table('student_module_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('student_module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['module_answer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['module_question.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['student_module_id'], ['student_module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_module_answer_id'), 'student_module_answer', ['id'], unique=False)
    op.create_table('student_seminar_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('student_seminar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['seminar_answer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['seminar_question.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['student_seminar_id'], ['student_seminar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_seminar_answer_id'), 'student_seminar_answer', ['id'], unique=False)
    op.create_table('student_test_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('student_test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['test_answer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['student_test_id'], ['student_test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_test_answer_id'), 'student_test_answer', ['id'], unique=False)
    op.create_table('test_feedback_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('test_feedback_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.ForeignKeyConstraint(['test_feedback_id'], ['test_feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_feedback_answer_id'), 'test_feedback_answer', ['id'], unique=False)
    op.create_table('test_matching_left',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['test_matching_right.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_matching_left_id'), 'test_matching_left', ['id'], unique=False)
    op.create_table('student_module_matching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('left_option_id', sa.Integer(), nullable=False),
    sa.Column('right_option_id', sa.Integer(), nullable=False),
    sa.Column('student_module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_option_id'], ['module_matching_left.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['module_question.id'], ),
    sa.ForeignKeyConstraint(['right_option_id'], ['module_matching_right.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['student_module_id'], ['student_module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_module_matching_id'), 'student_module_matching', ['id'], unique=False)
    op.create_table('student_seminar_matching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('left_option_id', sa.Integer(), nullable=True),
    sa.Column('right_option_id', sa.Integer(), nullable=True),
    sa.Column('student_seminar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_option_id'], ['seminar_matching_left.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['seminar_question.id'], ),
    sa.ForeignKeyConstraint(['right_option_id'], ['seminar_matching_right.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['student_seminar_id'], ['student_seminar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_seminar_matching_id'), 'student_seminar_matching', ['id'], unique=False)
    op.create_table('student_test_matching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('left_option_id', sa.Integer(), nullable=True),
    sa.Column('right_option_id', sa.Integer(), nullable=True),
    sa.Column('student_test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_option_id'], ['test_matching_left.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], ),
    sa.ForeignKeyConstraint(['right_option_id'], ['test_matching_right.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['student_test_id'], ['student_test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_test_matching_id'), 'student_test_matching', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_test_matching_id'), table_name='student_test_matching')
    op.drop_table('student_test_matching')
    op.drop_index(op.f('ix_student_seminar_matching_id'), table_name='student_seminar_matching')
    op.drop_table('student_seminar_matching')
    op.drop_index(op.f('ix_student_module_matching_id'), table_name='student_module_matching')
    op.drop_table('student_module_matching')
    op.drop_index(op.f('ix_test_matching_left_id'), table_name='test_matching_left')
    op.drop_table('test_matching_left')
    op.drop_index(op.f('ix_test_feedback_answer_id'), table_name='test_feedback_answer')
    op.drop_table('test_feedback_answer')
    op.drop_index(op.f('ix_student_test_answer_id'), table_name='student_test_answer')
    op.drop_table('student_test_answer')
    op.drop_index(op.f('ix_student_seminar_answer_id'), table_name='student_seminar_answer')
    op.drop_table('student_seminar_answer')
    op.drop_index(op.f('ix_student_module_answer_id'), table_name='student_module_answer')
    op.drop_table('student_module_answer')
    op.drop_index(op.f('ix_seminar_matching_left_id'), table_name='seminar_matching_left')
    op.drop_table('seminar_matching_left')
    op.drop_index(op.f('ix_seminar_feedback_answer_id'), table_name='seminar_feedback_answer')
    op.drop_table('seminar_feedback_answer')
    op.drop_index(op.f('ix_module_matching_left_id'), table_name='module_matching_left')
    op.drop_table('module_matching_left')
    op.drop_index(op.f('ix_test_matching_right_id'), table_name='test_matching_right')
    op.drop_table('test_matching_right')
    op.drop_index(op.f('ix_test_feedback_id'), table_name='test_feedback')
    op.drop_table('test_feedback')
    op.drop_index(op.f('ix_test_answer_id'), table_name='test_answer')
    op.drop_table('test_answer')
    op.drop_index(op.f('ix_seminar_matching_right_id'), table_name='seminar_matching_right')
    op.drop_table('seminar_matching_right')
    op.drop_index(op.f('ix_seminar_feedback_id'), table_name='seminar_feedback')
    op.drop_table('seminar_feedback')
    op.drop_index(op.f('ix_seminar_answer_id'), table_name='seminar_answer')
    op.drop_table('seminar_answer')
    op.drop_index(op.f('ix_module_matching_right_id'), table_name='module_matching_right')
    op.drop_table('module_matching_right')
    op.drop_index(op.f('ix_module_answer_id'), table_name='module_answer')
    op.drop_table('module_answer')
    op.drop_index(op.f('ix_lecture_value_id'), table_name='lecture_value')
    op.drop_table('lecture_value')
    op.drop_index(op.f('ix_lecture_files_id'), table_name='lecture_files')
    op.drop_table('lecture_files')
    op.drop_index(op.f('ix_video_seminar_score_id'), table_name='video_seminar_score')
    op.drop_table('video_seminar_score')
    op.drop_index(op.f('ix_video_lecture_score_id'), table_name='video_lecture_score')
    op.drop_table('video_lecture_score')
    op.drop_index(op.f('ix_test_question_id'), table_name='test_question')
    op.drop_table('test_question')
    op.drop_index(op.f('ix_student_test_id'), table_name='student_test')
    op.drop_table('student_test')
    op.drop_index(op.f('ix_student_seminar_id'), table_name='student_seminar')
    op.drop_table('student_seminar')
    op.drop_index(op.f('ix_student_module_id'), table_name='student_module')
    op.drop_table('student_module')
    op.drop_index(op.f('ix_seminar_question_id'), table_name='seminar_question')
    op.drop_table('seminar_question')
    op.drop_index(op.f('ix_module_question_id'), table_name='module_question')
    op.drop_table('module_question')
    op.drop_index(op.f('ix_lecture_score_id'), table_name='lecture_score')
    op.drop_table('lecture_score')
    op.drop_index(op.f('ix_lecture_attribute_id'), table_name='lecture_attribute')
    op.drop_table('lecture_attribute')
    op.drop_index(op.f('ix_video_seminar_id'), table_name='video_seminar')
    op.drop_table('video_seminar')
    op.drop_index(op.f('ix_video_lecture_id'), table_name='video_lecture')
    op.drop_table('video_lecture')
    op.drop_index(op.f('ix_test_lesson_id'), table_name='test_lesson')
    op.drop_table('test_lesson')
    op.drop_index(op.f('ix_subject_instruction_files_id'), table_name='subject_instruction_files')
    op.drop_table('subject_instruction_files')
    op.drop_index(op.f('ix_subject_chat_attach_file_id'), table_name='subject_chat_attach_file')
    op.drop_table('subject_chat_attach_file')
    op.drop_index(op.f('ix_seminar_id'), table_name='seminar')
    op.drop_table('seminar')
    op.drop_index(op.f('ix_module_control_id'), table_name='module_control')
    op.drop_table('module_control')
    op.drop_index(op.f('ix_lesson_score_id'), table_name='lesson_score')
    op.drop_table('lesson_score')
    op.drop_index(op.f('ix_lesson_missing_id'), table_name='lesson_missing')
    op.drop_table('lesson_missing')
    op.drop_index(op.f('ix_lecture_id'), table_name='lecture')
    op.drop_table('lecture')
    op.drop_index(op.f('ix_subject_recipient_id'), table_name='subject_recipient')
    op.drop_table('subject_recipient')
    op.drop_index(op.f('ix_subject_instruction_id'), table_name='subject_instruction')
    op.drop_table('subject_instruction')
    op.drop_index(op.f('ix_subject_chat_answer_id'), table_name='subject_chat_answer')
    op.drop_table('subject_chat_answer')
    op.drop_index(op.f('ix_lesson_id'), table_name='lesson')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_group_chat_attach_file_id'), table_name='group_chat_attach_file')
    op.drop_table('group_chat_attach_file')
    op.drop_table('subject_teacher_association')
    op.drop_index(op.f('ix_subject_item_id'), table_name='subject_item')
    op.drop_table('subject_item')
    op.drop_index(op.f('ix_subject_instruction_category_id'), table_name='subject_instruction_category')
    op.drop_table('subject_instruction_category')
    op.drop_index(op.f('ix_subject_icon_id'), table_name='subject_icon')
    op.drop_table('subject_icon')
    op.drop_index(op.f('ix_subject_chat_id'), table_name='subject_chat')
    op.drop_table('subject_chat')
    op.drop_table('student_additional_subject')
    op.drop_index(op.f('ix_participant_comment_id'), table_name='participant_comment')
    op.drop_table('participant_comment')
    op.drop_index(op.f('ix_module_id'), table_name='module')
    op.drop_table('module')
    op.drop_index(op.f('ix_message_recipient_id'), table_name='message_recipient')
    op.drop_table('message_recipient')
    op.drop_index(op.f('ix_group_chat_answer_id'), table_name='group_chat_answer')
    op.drop_table('group_chat_answer')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_table('student')
    op.drop_table('group_teacher_association')
    op.drop_index(op.f('ix_group_chat_id'), table_name='group_chat')
    op.drop_table('group_chat')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_teacher_id'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_moder_id'), table_name='moder')
    op.drop_table('moder')
    op.drop_index(op.f('ix_curator_id'), table_name='curator')
    op.drop_table('curator')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_specialization_id'), table_name='specialization')
    op.drop_table('specialization')
    op.drop_index(op.f('ix_user_type_id'), table_name='user_type')
    op.drop_table('user_type')
    op.drop_index(op.f('ix_question_type_id'), table_name='question_type')
    op.drop_table('question_type')
    op.drop_index(op.f('ix_module_control_type_id'), table_name='module_control_type')
    op.drop_table('module_control_type')
    op.drop_index(op.f('ix_course_id'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
