"""added field hided

Revision ID: 7dd6c230552b
Revises: 177b16487c61
Create Date: 2023-10-18 10:05:02.527428

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7dd6c230552b'
down_revision = '177b16487c61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_attribute', sa.Column('hided', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_attribute', 'hided')
    # ### end Alembic commands ###
