"""delete feedback

Revision ID: 8715dd6de798
Revises: 7dd6c230552b
Create Date: 2023-10-24 15:30:58.130368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8715dd6de798'
down_revision = '7dd6c230552b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seminar_feedback_answer_id', table_name='seminar_feedback_answer')
    op.drop_table('seminar_feedback_answer')
    op.drop_index('ix_seminar_feedback_id', table_name='seminar_feedback')
    op.drop_table('seminar_feedback')
    op.drop_index('ix_test_feedback_id', table_name='test_feedback')
    op.drop_table('test_feedback')
    op.drop_index('ix_test_feedback_answer_id', table_name='test_feedback_answer')
    op.drop_table('test_feedback_answer')
    op.add_column('lecture_files', sa.Column('file_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_files', 'file_description')
    op.create_table('test_feedback_answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('answer', sa.VARCHAR(), nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.Column('test_feedback_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.ForeignKeyConstraint(['test_feedback_id'], ['test_feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_feedback_answer_id', 'test_feedback_answer', ['id'], unique=False)
    op.create_table('test_feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_feedback_id', 'test_feedback', ['id'], unique=False)
    op.create_table('seminar_feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['seminar_question.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seminar_feedback_id', 'seminar_feedback', ['id'], unique=False)
    op.create_table('seminar_feedback_answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('answer', sa.VARCHAR(), nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.Column('seminar_feedback_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['seminar_feedback_id'], ['seminar_feedback.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seminar_feedback_answer_id', 'seminar_feedback_answer', ['id'], unique=False)
    # ### end Alembic commands ###
