"""Update tables

Revision ID: 8bd948f46c16
Revises: bce6e23850d6
Create Date: 2023-10-12 11:54:54.241207

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8bd948f46c16'
down_revision = 'bce6e23850d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template', sa.JSON(), nullable=False),
    sa.Column('basis', sa.Enum('lecture', 'seminar', 'test', 'online_lecture', 'online_seminar', 'module_control', 'exam', name='lessontypeoption'), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_template_id'), 'teacher_template', ['id'], unique=False)
    op.add_column('test_answer', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('test_lesson', sa.Column('min_score', sa.Integer(), nullable=True))
    op.add_column('test_lesson', sa.Column('shuffle_answer', sa.Boolean(), nullable=True))
    op.add_column('test_question', sa.Column('hided', sa.Boolean(), autoincrement=True, nullable=False))
    op.add_column('test_question', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_question', 'image_path')
    op.drop_column('test_question', 'hided')
    op.drop_column('test_lesson', 'shufle_answer')
    op.drop_column('test_lesson', 'min_score')
    op.drop_column('test_answer', 'image_path')
    op.drop_index(op.f('ix_teacher_template_id'), table_name='teacher_template')
    op.drop_table('teacher_template')
    # ### end Alembic commands ###
