"""Create ModuleControl Tables

Revision ID: 9cf44218f00d
Revises: ba6a411625e6
Create Date: 2023-07-19 15:39:47.545457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf44218f00d'
down_revision = 'ba6a411625e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
