"""Updae exp_token field

Revision ID: a522c4cf012c
Revises: 452afbd9e874
Create Date: 2023-06-02 10:07:49.471668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a522c4cf012c'
down_revision = '452afbd9e874'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
