"""Added new table SubjectInstructionLink

Revision ID: bce6e23850d6
Revises: 7b022dfc5068
Create Date: 2023-09-29 16:51:38.941388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce6e23850d6'
down_revision = '7b022dfc5068'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_instruction_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_instruction_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_instruction_id'], ['subject_instruction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_instruction_link_id'), 'subject_instruction_link', ['id'], unique=False)
    op.add_column('group_chat', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('group_chat_answer', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('subject_chat', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('subject_chat_answer', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('subject_instruction_files', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_chat_answer', 'deleted')
    op.drop_column('subject_chat', 'deleted')
    op.drop_column('group_chat_answer', 'deleted')
    op.drop_column('group_chat', 'deleted')
    op.drop_index(op.f('ix_subject_instruction_link_id'), table_name='subject_instruction_link')
    op.drop_table('subject_instruction_link')
    # ### end Alembic commands ###
