"""added table subject_icon

Revision ID: bde25f8ee3a8
Revises: 17cbff25c501
Create Date: 2023-08-10 11:49:47.106721

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bde25f8ee3a8'
down_revision = '17cbff25c501'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_icon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon_path', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_icon_id'), 'subject_icon', ['id'], unique=False)
    op.create_index(op.f('ix_subject_item_id'), 'subject_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_item_id'), table_name='subject_item')
    op.drop_index(op.f('ix_subject_icon_id'), table_name='subject_icon')
    op.drop_table('subject_icon')
    # ### end Alembic commands ###
