"""Remove is_viewed column from message_recipient table

Revision ID: ec395377a76f
Revises: f25ed94fa50d
Create Date: 2023-07-10 15:19:33.290125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec395377a76f'
down_revision = 'f25ed94fa50d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_recipient', 'is_viewed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_recipient', sa.Column('is_viewed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
